[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_SUPABASE_URL = "https://gytxomjiashbrdbsoxze.supabase.co"
  VITE_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_XgSYdszKIZCCXpmzbpcfCg_5KJCZizx"
